name: Java CI Test

on:
  push:
    paths: ["src/**/*.java"]
    branches: [ "main" ]
  pull_request:
    paths: ["src/**/*.java"]
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version-file: '.java-version'
          distribution: oracle

      - name: Test
          run: ./gradlew test