name: Java CI Test

on:
  push:
    paths: ["src/**/*.java", '.github/workflows/*.yaml']
    branches: [ "main" ]
  pull_request:
    paths: ["src/**/*.java", '.github/workflows/*.yaml']
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version-file: '.java-version'
          distribution: oracle
          cache: gradle

      - name: Test
        run: ./gradlew test